services: 
  source_postgres:

#The course suggested to have postgres updated to the latest, however, it is not updated
# To ensure compatibility, postgres would need to be at 9.2

    # image: postgres:latest
    image: postgres:9.2
    ports:
      - "5433:5432"
    networks: 
      - elt_network
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes: 
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
  

  destination_postgres:
    # image: postgres:latest
    image: postgres:9.2
    ports:
      - "5434:5432"
    networks: 
      - elt_network
    environment:
      POSTGRES_DB: destination_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
  
  # not in use as airflow is using it

  # elt_script: 
  #   build: 
  #     context: ./elt
  #     dockerfile: Dockerfile
  #   command: [ "python", "elt_script.py" ]
  #   networks: 
  #     - elt_network
  #   depends_on:
  #     - source_postgres
  #     - destination_postgres

  # dbt: 
  #   image: ghcr.io/dbt-labs/dbt-postgres:1.4.7
  #   command: 
  #     [
  #       "run",
  #       "--profiles-dir",
  #       "/root",
  #       "--project-dir",
  #       "/dbt"
  #     ]
  #   networks:
  #     - elt_network
  #   volumes:
  #     - ./custom_postgres:/dbt
  #     - ~/dbt:/root
  #   depends_on: 
  #     - elt_script
  #   environment:
  #     DBT_PROFILE: default
  #     DBT_TARGET: dev

  postgres:
    image: postgres:latest
    networks: 
      - elt_network
    environment:
      - POSTGRES_USER = airflow
      - POSTGRES_PASSWORD = airflow
      - POSTGRES_DB = airflow

# initialisation of airflow
  init-airflow: 
    image: apache/airflow:latest
    depends_on: 
      - postgres
    networks: 
      -elt_network
    environment: 
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN = postgres+psycopg2://airflow:airflow@postgres/airflow
    command: > 
      bash -c "airflow db init && 
               users create --username airflow --password password --firstname john --lastname doe --role admin --email admin@mail.com"


# UI OF AIRFLOW
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    depends_on: 
      - postgres
    networks:
      - elt_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes: 
      - ./airflow/dags:/opt/airflow/dags
      - ./elt:/opt/airflow/elt
      - ./custom_postgres:/opt/dbt
      - ~/.dbt:/root/.dbt
      - /var/run/docker.sock:/var/run/docker.sock

    environments:
      - LOAD_EN=n
      - EXECUTOR=Local
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN = postgres+psycopg2://airflow:airflow@postgres/airflow
      # encrypts username and password
      # - AIRFLOW__CORRE__FERNET_KEY=
      - AIRFLOW__WEBSERVER__DEFAULT__USER_USERNAME = airflow
      - AIRFLOW__WEBSERVER__DEFAULT__PASSWORD = password
      - AIRFLOW_WWW_USER_USERNAME= airflow
      - AIRFLOW_WWW_USER_PASSWORD= password
      - AIRFLOW__WEBSERVER__SECRET_KEY=secret

    ports:
    - "8080:8080"
    command: webserver

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    depends_on: 
      - postgres
    networks:
      - elt_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes: 
      - ./airflow/dags:/opt/airflow/dags
      - ./elt:/opt/airflow/elt
      - ./custom_postgres:/opt/dbt
      - ~/.dbt:/root/.dbt
      - /var/run/docker.sock:/var/run/docker.sock

    environments:
      - LOAD_EN=n
      - EXECUTOR=Local
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN = postgres+psycopg2://airflow:airflow@postgres/airflow
      # encrypts username and password
      # - AIRFLOW__CORRE__FERNET_KEY=
      - AIRFLOW__WEBSERVER__DEFAULT__USER_USERNAME = airflow
      - AIRFLOW__WEBSERVER__DEFAULT__PASSWORD = password
      - AIRFLOW_WWW_USER_USERNAME= airflow
      - AIRFLOW_WWW_USER_PASSWORD= password
      - AIRFLOW__WEBSERVER__SECRET_KEY=secret

    ports:
    - "8080:8080"
    command: scheduler




networks:
  elt_network:
    driver: bridge


