
version: 2

models:
  - name: films
    description: "This table contains details about films"
    columns:
      - name: film_id
        description: "unique identifier for film"
        tests:
          - unique
          - not_null
      - name: title
        description: "film title"
        tests:
          - not_null
      - name: release_date
        description: "date of film release"
        tests:
          - not_null
      - name: price
        description: "price of ticket"
        tests:
          - not_null
      - name: rating
        description: "MPAA rating of film"
        tests:
          - not_null
      - name: user_rating
        description: "rating users gave the film"
        tests:
          - not_null

  - name: actors
    description: "This table contains details about actors"
    columns:
      - name: actor_id
        description: "unique identifier for the actor"
        tests:
          - unique
          - not_null
      - name: name
        description: "first name of actor"
        tests:

  - name: film_actors
    description: "This table maps films to actors that starred in them"
    columns:
      - name: film_id
        description: "identifier for the film"
        tests:
          - not_null
      - name: actor_id
        description: "unique identifier for the actor"
        tests:
          - not_null

  - name: film_ratings
    description: "This model aggregates film data and calculates the average rating for each film"
    columns:
      - name: film_id
        description: "unique identifier for film"
        tests:
          - unique
          - not_null
      - name: title
        description: "film title"
        tests:
          - not_null
      - name: release_date
        description: "date of film release"
        tests:
          - not_null
      - name: price
        description: "price of ticket"
        tests:
          - not_null
      - name: rating
        description: "MPAA rating of film"
        tests:
          - not_null
          
      - name: user_rating
        description: "rating users gave of film"
        tests:
          - not_null
      - name: actor_count
        description: "number of actors in film"
        tests:
          - not_null
      - name: avg_actor_rating
        description: "Average rating of all films that the actors of this film have acted in"
        tests:
          - not_null

